# Generated by Django 5.2.12 on 2026-03-19 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(help_text='Ex: Porta Principal - Apto 201', max_length=100)),
                ('id_dispositivo', models.CharField(help_text='ID/MAC do ESP32 para MQTT', max_length=50, unique=True)),
                ('esta_online', models.BooleanField(default=False)),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechaduras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcessoTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospede_identificador', models.EmailField(help_text='E-mail do hóspede para validação', max_length=254)),
                ('token_resgate', models.CharField(default='6D7710128050', max_length=12, unique=True)),
                ('inicio_reserva', models.DateTimeField()),
                ('fim_reserva', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Resgate'), ('AGENDADO', 'Resgate Concluído / Aguardando Data'), ('ATIVO', 'Acesso Autorizado'), ('EXPIRADO', 'Prazo Encerrado'), ('REVOGADO', 'Cancelado pelo Anfitrião')], default='PENDENTE', max_length=10)),
                ('resgatado_em', models.DateTimeField(blank=True, null=True)),
                ('hospede_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minhas_chaves', to=settings.AUTH_USER_MODEL)),
                ('fechadura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='access_control.fechadura')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACESSO', 'Abertura de Porta'), ('ALERTA_GAS', 'Detecção de Gás'), ('ALERTA_FUMACA', 'Detecção de Fumaça'), ('SISTEMA', 'Status do Dispositivo')], max_length=20)),
                ('valor_sensor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fechadura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='access_control.fechadura')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
