# Generated by Django 5.2.12 on 2026-04-10 22:29

import access_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessotemporario',
            name='token_resgate',
            field=models.CharField(default=access_control.models.gerar_token, max_length=12, unique=True),
        ),
    ]
